### ISSUE TITLE
New logo project

### ISSUE THREAD

**Issue by nightsoundars** [messutied/colors.sh#4]
Hello! I want to contribute on your project with making logo design. What do you think about it?

**Comment by messutied** [comment]
Sure, what do you have in mind?

**Comment by nightsoundars** [comment]
Hi Eduardo 
https://drive.google.com/open?id=1xuBOi7bxfUSV7AOg0TCH_OPULMXDrqoO

**Comment by messutied** [comment]
Thanks but I think the emoji used currently is nice enough :)
